/*  Creator: make/0

    Purpose: Provide index for autoload
*/

index((add_later), 1, mpred_agenda, mpred_agenda).
index((after_mpred_load_pass2), 0, mpred_agenda, mpred_agenda).
index((agenda_do_prequery), 0, mpred_agenda, mpred_agenda).
index((agenda_mpred_repropigate), 0, mpred_agenda, mpred_agenda).
index((agenda_rescan_for_module_ready), 0, mpred_agenda, mpred_agenda).
index((agenda_rescan_mpred_ops), 0, mpred_agenda, mpred_agenda).
index((agenda_slow_op_enqueue), 1, mpred_agenda, mpred_agenda).
index((agenda_slow_op_restart), 0, mpred_agenda, mpred_agenda).
index((agenda_slow_op_todo), 1, mpred_agenda, mpred_agenda).
index((assertOnLoad), 1, mpred_agenda, mpred_agenda).
index((assert_next), 2, mpred_agenda, mpred_agenda).
index((call_after), 2, mpred_agenda, mpred_agenda).
index((call_after_mpred_load), 1, mpred_agenda, mpred_agenda).
index((call_after_mpred_load_slow), 1, mpred_agenda, mpred_agenda).
index((call_after_next), 2, mpred_agenda, mpred_agenda).
index((do_all_of), 1, mpred_agenda, mpred_agenda).
index((do_all_of_ilc), 1, mpred_agenda, mpred_agenda).
index((do_all_of_when), 1, mpred_agenda, mpred_agenda).
index((do_call_OnEachLoad), 0, mpred_agenda, mpred_agenda).
index((do_stuff_of_ilc), 1, mpred_agenda, mpred_agenda).
index((doing_agenda_slow_op), 0, mpred_agenda, mpred_agenda).
index((englishServerInterface), 1, mpred_agenda, mpred_agenda).
index((ensure_at_least_one_region), 0, mpred_agenda, mpred_agenda).
index((expire_post_change), 2, mpred_agenda, mpred_agenda).
index((expire_pre_change), 2, mpred_agenda, mpred_agenda).
index((finish_processing_dbase), 0, mpred_agenda, mpred_agenda).
index((gather_fact_heads), 2, mpred_agenda, mpred_agenda).
index((kb_db_op), 2, mpred_agenda, mpred_agenda).
index((more_to_do), 1, mpred_agenda, mpred_agenda).
index((mpred_one_minute_timer), 0, mpred_agenda, mpred_agenda).
index((mpred_one_second_timer), 0, mpred_agenda, mpred_agenda).
index((onEachLoad), 1, mpred_agenda, mpred_agenda).
index((onLoad), 1, mpred_agenda, mpred_agenda).
index((reduce_fact_heads), 4, mpred_agenda, mpred_agenda).
index((register_timer_thread), 3, mpred_agenda, mpred_agenda).
index((rerun_database_hooks), 0, mpred_agenda, mpred_agenda).
index((rescan_all), 0, mpred_agenda, mpred_agenda).
index((rescan_duplicated_facts), 0, mpred_agenda, mpred_agenda).
index((rescan_duplicated_facts), 2, mpred_agenda, mpred_agenda).
index((rescan_duplicated_facts), 3, mpred_agenda, mpred_agenda).
index((rescan_mpred_facts_local), 0, mpred_agenda, mpred_agenda).
index((rescan_mpred_loaded), 0, mpred_agenda, mpred_agenda).
index((rescan_mpred_loaded_pass2), 0, mpred_agenda, mpred_agenda).
index((rescandb), 0, mpred_agenda, mpred_agenda).
index((run_database_hooks), 2, mpred_agenda, mpred_agenda).
index((run_database_hooks_0), 2, mpred_agenda, mpred_agenda).
index((run_database_hooks_depth_1), 2, mpred_agenda, mpred_agenda).
index((setTemplate), 1, mpred_agenda, mpred_agenda).
index((show_cgoal), 1, mpred_agenda, mpred_agenda).
index((start_one_minute_timer), 0, mpred_agenda, mpred_agenda).
index((start_one_second_timer), 0, mpred_agenda, mpred_agenda).
index((suspend_timers), 0, mpred_agenda, mpred_agenda).
index((tick_every), 3, mpred_agenda, mpred_agenda).
index((time_tick), 2, mpred_agenda, mpred_agenda).
index((wfAssert), 1, mpred_agenda, mpred_agenda).
index((mpred_agenda_file), 0, mpred_agenda, mpred_agenda).
index((assert_setting01), 1, mpred_at_box, mpred_at_box).
index((create_predicate_istAbove), 3, mpred_at_box, mpred_at_box).
index((make_module_name_local), 2, mpred_at_box, mpred_at_box).
index((make_module_name_local0), 2, mpred_at_box, mpred_at_box).
index((make_shared_multifile), 3, mpred_at_box, mpred_at_box).
index((make_shared_multifile), 4, mpred_at_box, mpred_at_box).
index((add_import_predicate), 3, mpred_at_box, mpred_at_box).
index((autoload_library_index), 4, mpred_at_box, mpred_at_box).
index((ensure_abox), 1, mpred_at_box, mpred_at_box).
index((baseKB_hybrid_support), 2, mpred_at_box, mpred_at_box).
index((uses_predicate), 2, mpred_at_box, mpred_at_box).
index((uses_predicate), 5, mpred_at_box, mpred_at_box).
index((correct_module), 3, mpred_at_box, mpred_at_box).
index((correct_module), 5, mpred_at_box, mpred_at_box).
index((defaultAssertMt), 1, mpred_at_box, mpred_at_box).
index((ensure_imports), 1, mpred_at_box, mpred_at_box).
index((is_parent_goal), 1, mpred_at_box, mpred_at_box).
index((is_parent_goal), 2, mpred_at_box, mpred_at_box).
index((has_parent_goal), 1, mpred_at_box, mpred_at_box).
index((has_parent_goal), 2, mpred_at_box, mpred_at_box).
index((fileAssertMt), 1, mpred_at_box, mpred_at_box).
index((setup_module_ops), 1, mpred_at_box, mpred_at_box).
index((in_mpred_kb_module), 0, mpred_at_box, mpred_at_box).
index((istAbove), 2, mpred_at_box, mpred_at_box).
index((make_as_dynamic), 4, mpred_at_box, mpred_at_box).
index((makeConstant), 1, mpred_at_box, mpred_at_box).
index((mtCanAssert), 1, mpred_at_box, mpred_at_box).
index((retry_undefined), 3, mpred_at_box, mpred_at_box).
index((set_defaultAssertMt), 1, mpred_at_box, mpred_at_box).
index((set_fileAssertMt), 1, mpred_at_box, mpred_at_box).
index((transitive_path), 3, mpred_at_box, mpred_at_box).
index((which_file), 1, mpred_at_box, mpred_at_box).
index((user_m_check), 1, mpred_at_box, mpred_at_box).
index((add_abox_module), 1, mpred_at_box, mpred_at_box).
index((ensure_tbox), 1, mpred_at_box, mpred_at_box).
index((get_file_type_local), 2, mpred_at_box, mpred_at_box).
index((fixup_modules), 0, mpred_at_box, mpred_at_box).
index((import_predicate), 2, mpred_at_box, mpred_at_box).
index((skip_user), 1, mpred_at_box, mpred_at_box).
index((inherit_into_module), 2, mpred_at_box, mpred_at_box).
index((box_type), 3, mpred_at_box, mpred_at_box).
index((make_reachable), 2, mpred_at_box, mpred_at_box).
index((fixup_module), 2, mpred_at_box, mpred_at_box).
index((is_undefaulted), 1, mpred_at_box, mpred_at_box).
index((ensure_imports_tbox), 2, mpred_at_box, mpred_at_box).
index((map_inheritance), 1, mpred_at_box, mpred_at_box).
index((which_file), 1, mpred_at_box, mpred_at_box).
index((call_u_no_bc), 1, mpred_core, mpred_core).
index((fix_mp), 4, mpred_core, mpred_core).
index((mpred_fwc), 1, mpred_core, mpred_core).
index((get_mpred_is_tracing), 1, mpred_core, mpred_core).
index((show_if_debug), 1, mpred_core, mpred_core).
index((full_transform_warn_if_changed), 3, mpred_core, mpred_core).
index((full_transform_warn_if_same), 3, mpred_core, mpred_core).
index((full_transform), 3, mpred_core, mpred_core).
index((maybe_mpred_break), 1, mpred_core, mpred_core).
index((each_E), 3, mpred_core, mpred_core).
index((call_m_g), 3, mpred_core, mpred_core).
index((same_modules), 2, mpred_core, mpred_core).
index((throw_depricated), 0, mpred_core, mpred_core).
index((mpred_post_exactly), 1, mpred_core, mpred_core).
index((lookup_m_g), 3, mpred_core, mpred_core).
index((head_to_functor_name), 2, mpred_core, mpred_core).
index((ain_expanded), 1, mpred_core, mpred_core).
index((mpred_notrace_exec), 0, mpred_core, mpred_core).
index((get_consequent_functor), 3, mpred_core, mpred_core).
index((mpred_post1_rem), 2, mpred_core, mpred_core).
index((mpred_post1), 1, mpred_core, mpred_core).
index((mpred_post1_rem1), 2, mpred_core, mpred_core).
index((mpred_post2), 2, mpred_core, mpred_core).
index((mpred_post12), 2, mpred_core, mpred_core).
index((fwc1s_post1s), 2, mpred_core, mpred_core).
index((mpred_mark_as_ml), 3, mpred_core, mpred_core).
index((mpred_mark_fa_as), 5, mpred_core, mpred_core).
index((maybe_updated_value), 3, mpred_core, mpred_core).
index((log_failure), 1, mpred_core, mpred_core).
index((code_sentence_op), 1, mpred_core, mpred_core).
index((mnotrace), 1, mpred_core, mpred_core).
index((mpred_compile_rhs_term_consquent), 3, mpred_core, mpred_core).
index((with_fc_mode), 2, mpred_core, mpred_core).
index((filter_buffer_n_test), 3, mpred_core, mpred_core).
index((filter_buffer_get_n), 3, mpred_core, mpred_core).
index((filter_buffer_trim), 2, mpred_core, mpred_core).
index((plus_fwc), 0, mpred_core, mpred_core).
index((plus_fwc), 1, mpred_core, mpred_core).
index((cut_c), 0, mpred_core, mpred_core).
index((to_u), 2, mpred_core, mpred_core).
index((fresh_mode), 0, mpred_core, mpred_core).
index((mpred_mark_as), 3, mpred_core, mpred_core).
index((get_first_user_reason), 2, mpred_core, mpred_core).
index((assert_u_confirm_if_missing), 1, mpred_core, mpred_core).
index((assert_u_confirmed_was_missing), 1, mpred_core, mpred_core).
index((mpred_notrace_exec), 0, mpred_core, mpred_core).
index((remove_negative_version), 1, mpred_core, mpred_core).
index((listing_u), 1, mpred_core, mpred_core).
index((call_u_mp), 2, mpred_core, mpred_core).
index((call_u_mp_fa), 4, mpred_core, mpred_core).
index((call_u_mp_lc), 4, mpred_core, mpred_core).
index((=@@=), 2, mpred_core, mpred_core).
index((get_source_ref), 1, mpred_core, mpred_core).
index((get_source_ref1), 1, mpred_core, mpred_core).
index((get_source_ref10), 1, mpred_core, mpred_core).
index((is_source_ref1), 1, mpred_core, mpred_core).
index((get_source_ref_stack), 1, mpred_core, mpred_core).
index((set_fc_mode), 1, mpred_core, mpred_core).
index((with_no_mpred_breaks), 1, mpred_core, mpred_core).
index((mpred_remove1), 2, mpred_core, mpred_core).
index((check_never_assert), 1, mpred_core, mpred_core).
index((check_never_retract), 1, mpred_core, mpred_core).
index((oinfo), 1, mpred_core, mpred_core).
index((why_was_true), 1, mpred_core, mpred_core).
index((mpred_fwc0), 1, mpred_core, mpred_core).
index((with_no_mpred_trace_exec), 1, mpred_core, mpred_core).
index((mpred_set_default), 2, mpred_core, mpred_core).
index((mpred_ain), 1, mpred_core, mpred_core).
index((mpred_ain), 1, mpred_core, mpred_core).
index((mpred_ain), 2, mpred_core, mpred_core).
index((action_is_undoable), 1, mpred_core, mpred_core).
index((mpred_assumption), 1, mpred_core, mpred_core).
index((mpred_assumptions), 2, mpred_core, mpred_core).
index((mpred_axiom), 1, mpred_core, mpred_core).
index((bagof_or_nil), 3, mpred_core, mpred_core).
index((bases_union), 2, mpred_core, mpred_core).
index((brake), 1, mpred_core, mpred_core).
index((build_rhs), 3, mpred_core, mpred_core).
index((mpred_BC_CACHE0), 2, mpred_core, mpred_core).
index((build_neg_test), 4, mpred_core, mpred_core).
index((build_rule), 3, mpred_core, mpred_core).
index((build_code_test), 3, mpred_core, mpred_core).
index((build_trigger), 4, mpred_core, mpred_core).
index((defaultmpred_select), 1, mpred_core, mpred_core).
index((fc_eval_action), 2, mpred_core, mpred_core).
index((foreachl_do), 2, mpred_core, mpred_core).
index((get_next_fact), 1, mpred_core, mpred_core).
index((justification), 2, mpred_core, mpred_core).
index((justifications), 2, mpred_core, mpred_core).
index((call_u), 1, mpred_core, mpred_core).
index((variant_u), 2, mpred_core, mpred_core).
index((mpred_BC_CACHE), 2, mpred_core, mpred_core).
index((call_u_no_bc), 1, mpred_core, mpred_core).
index((mpred_METACALL), 2, mpred_core, mpred_core).
index((mpred_METACALL), 3, mpred_core, mpred_core).
index((mpred_METACALL), 3, mpred_core, mpred_core).
index((mpred_halt), 0, mpred_core, mpred_core).
index((mpred_halt), 1, mpred_core, mpred_core).
index((mpred_halt), 2, mpred_core, mpred_core).
index((mpred_ain_db_to_head), 2, mpred_core, mpred_core).
index((mpred_ain_actiontrace), 2, mpred_core, mpred_core).
index((mpred_trace_op), 2, mpred_core, mpred_core).
index((mpred_add_support), 2, mpred_core, mpred_core).
index((mpred_ain_trigger_reprop), 2, mpred_core, mpred_core).
index((mpred_ain_by_type), 2, mpred_core, mpred_core).
index((mpred_prompt_ask), 2, mpred_core, mpred_core).
index((mpred_METACALL), 3, mpred_core, mpred_core).
index((mpred_BC_w_cache), 2, mpred_core, mpred_core).
index((ain_fast), 1, mpred_core, mpred_core).
index((ain_fast), 2, mpred_core, mpred_core).
index((setup_mpred_ops), 0, mpred_core, mpred_core).
index((mpred_assert_w_support), 2, mpred_core, mpred_core).
index((mpred_asserta_w_support), 2, mpred_core, mpred_core).
index((mpred_assertz_w_support), 2, mpred_core, mpred_core).
index((mpred_basis_list), 2, mpred_core, mpred_core).
index((mpred_bt_pt_combine), 3, mpred_core, mpred_core).
index((mpred_child), 2, mpred_core, mpred_core).
index((mpred_children), 2, mpred_core, mpred_core).
index((mpred_classifyFacts), 4, mpred_core, mpred_core).
index((mpred_collect_supports), 1, mpred_core, mpred_core).
index((mpred_unhandled_command), 3, mpred_core, mpred_core).
index((mpred_compile_rhs_term), 3, mpred_core, mpred_core).
index((mpred_conjoin), 3, mpred_core, mpred_core).
index((mpred_neg_connective), 1, mpred_core, mpred_core).
index((mpred_database_item), 1, mpred_core, mpred_core).
index((mpred_database_term), 3, mpred_core, mpred_core).
index((mpred_db_type), 2, mpred_core, mpred_core).
index((mpred_set_default), 2, mpred_core, mpred_core).
index((mpred_define_bc_rule), 3, mpred_core, mpred_core).
index((mpred_descendant), 2, mpred_core, mpred_core).
index((mpred_descendants), 2, mpred_core, mpred_core).
index((mpred_enqueue), 2, mpred_core, mpred_core).
index((mpred_error), 1, mpred_core, mpred_core).
index((mpred_error), 2, mpred_core, mpred_core).
index((mpred_eval_lhs), 2, mpred_core, mpred_core).
index((mpred_eval_lhs_0), 2, mpred_core, mpred_core).
index((mpred_eval_rhs), 2, mpred_core, mpred_core).
index((mpred_fact), 1, mpred_core, mpred_core).
index((mpred_fact), 2, mpred_core, mpred_core).
index((mpred_facts), 1, mpred_core, mpred_core).
index((mpred_facts), 2, mpred_core, mpred_core).
index((mpred_facts), 3, mpred_core, mpred_core).
index((mpred_fwc), 1, mpred_core, mpred_core).
index((mpred_get_support), 2, mpred_core, mpred_core).
index((lookup_u), 1, mpred_core, mpred_core).
index((lookup_u), 2, mpred_core, mpred_core).
index((mpred_literal), 1, mpred_core, mpred_core).
index((mpred_load), 1, mpred_core, mpred_core).
index((mpred_make_supports), 1, mpred_core, mpred_core).
index((mpred_ain_object), 1, mpred_core, mpred_core).
index((mpred_aina), 2, mpred_core, mpred_core).
index((mpred_ainz), 2, mpred_core, mpred_core).
index((mpred_aina), 1, mpred_core, mpred_core).
index((mpred_ainz), 1, mpred_core, mpred_core).
index((mpred_negated_literal), 1, mpred_core, mpred_core).
index((mpred_unnegate), 2, mpred_core, mpred_core).
index((mpred_nf), 2, mpred_core, mpred_core).
index((mpred_nf1_negation), 2, mpred_core, mpred_core).
index((mpred_nf_negation), 2, mpred_core, mpred_core).
index((mpred_nf_negations), 2, mpred_core, mpred_core).
index((mpred_notrace), 0, mpred_core, mpred_core).
index((mpred_nowatch), 0, mpred_core, mpred_core).
index((mpred_nospy), 0, mpred_core, mpred_core).
index((mpred_nospy), 1, mpred_core, mpred_core).
index((mpred_nospy), 3, mpred_core, mpred_core).
index((mpred_positive_literal), 1, mpred_core, mpred_core).
index((mpred_post), 2, mpred_core, mpred_core).
index((pp_qu), 0, mpred_core, mpred_core).
index((mpred_undo_action), 1, mpred_core, mpred_core).
index((mpred_rem_support), 2, mpred_core, mpred_core).
index((mpred_remove_old_version), 1, mpred_core, mpred_core).
index((mpred_remove_supports), 1, mpred_core, mpred_core).
index((mpred_remove_supports_quietly), 1, mpred_core, mpred_core).
index((mpred_reset), 0, mpred_core, mpred_core).
index((mpred_retract), 1, mpred_core, mpred_core).
index((mpred_retract_i_or_warn), 1, mpred_core, mpred_core).
index((mpred_retract_supported_relations), 1, mpred_core, mpred_core).
index((mpred_retract_type), 2, mpred_core, mpred_core).
index((mpred_select_justification_node), 3, mpred_core, mpred_core).
index((mpred_set_warnings), 1, mpred_core, mpred_core).
index((mpred_pp_db_justifications), 2, mpred_core, mpred_core).
index((mpred_spy), 1, mpred_core, mpred_core).
index((mpred_spy), 2, mpred_core, mpred_core).
index((mpred_spy), 3, mpred_core, mpred_core).
index((mpred_step), 0, mpred_core, mpred_core).
index((mpred_support_relation), 1, mpred_core, mpred_core).
index((mpred_supported), 1, mpred_core, mpred_core).
index((mpred_supported), 2, mpred_core, mpred_core).
index((mpred_trace), 0, mpred_core, mpred_core).
index((mpred_trace), 1, mpred_core, mpred_core).
index((mpred_trace), 2, mpred_core, mpred_core).
index((mpred_trace_maybe_print), 3, mpred_core, mpred_core).
index((mpred_trace_maybe_break), 3, mpred_core, mpred_core).
index((mpred_trace_exec), 0, mpred_core, mpred_core).
index((mpred_trace_op), 3, mpred_core, mpred_core).
index((mpred_trace_op), 2, mpred_core, mpred_core).
index((mpred_trace_msg), 1, mpred_core, mpred_core).
index((mpred_trace_msg), 2, mpred_core, mpred_core).
index((mpred_trigger_key), 2, mpred_core, mpred_core).
index((mpred_trigger_key), 2, mpred_core, mpred_core).
index((mpred_undo), 1, mpred_core, mpred_core).
index((mpred_unfwc), 1, mpred_core, mpred_core).
index((mpred_unfwc_check_triggers), 1, mpred_core, mpred_core).
index((mpred_union), 3, mpred_core, mpred_core).
index((mpred_unique_u), 1, mpred_core, mpred_core).
index((mpred_untrace), 0, mpred_core, mpred_core).
index((mpred_untrace), 1, mpred_core, mpred_core).
index((mpred_warn), 0, mpred_core, mpred_core).
index((mpred_warn), 1, mpred_core, mpred_core).
index((mpred_warn), 2, mpred_core, mpred_core).
index((mpred_watch), 0, mpred_core, mpred_core).
index((well_founded_0), 2, mpred_core, mpred_core).
index((clear_proofs), 0, mpred_core, mpred_core).
index((mpred_why), 0, mpred_core, mpred_core).
index((mpred_why), 1, mpred_core, mpred_core).
index((mpred_whyBrouse), 2, mpred_core, mpred_core).
index((mpred_handle_why_command), 3, mpred_core, mpred_core).
index((nompred_warn), 0, mpred_core, mpred_core).
index((pfcl_do), 1, mpred_core, mpred_core).
index((pp_DB), 0, mpred_core, mpred_core).
index((pp_db_facts), 0, mpred_core, mpred_core).
index((pp_db_facts), 1, mpred_core, mpred_core).
index((pp_db_facts), 2, mpred_core, mpred_core).
index((pp_db_items), 1, mpred_core, mpred_core).
index((pp_db_rules), 0, mpred_core, mpred_core).
index((pp_db_supports), 0, mpred_core, mpred_core).
index((pp_db_triggers), 0, mpred_core, mpred_core).
index((mpred_load), 1, mpred_core, mpred_core).
index((process_rule), 3, mpred_core, mpred_core).
index((remove_if_unsupported), 1, mpred_core, mpred_core).
index((remove_selection), 1, mpred_core, mpred_core).
index((mpred_withdraw1), 2, mpred_core, mpred_core).
index((mpred_post1), 2, mpred_core, mpred_core).
index((get_mpred_assertion_status), 3, mpred_core, mpred_core).
index((mpred_post_update4), 4, mpred_core, mpred_core).
index((get_mpred_support_status), 5, mpred_core, mpred_core).
index((same_file_facts), 2, mpred_core, mpred_core).
index((clause_asserted_u), 1, mpred_core, mpred_core).
index((mpred_run), 0, mpred_core, mpred_core).
index((mpred_test), 1, mpred_core, mpred_core).
index((mpred_test_fok), 1, mpred_core, mpred_core).
index((fa_to_p), 3, mpred_core, mpred_core).
index((call_u_no_bc), 1, mpred_core, mpred_core).
index((with_umt), 2, mpred_core, mpred_core).
index((asserta_u), 1, mpred_core, mpred_core).
index((assert_u), 1, mpred_core, mpred_core).
index((assertz_u), 1, mpred_core, mpred_core).
index((retract_u), 1, mpred_core, mpred_core).
index((retractall_u), 1, mpred_core, mpred_core).
index((retract_u0), 1, mpred_core, mpred_core).
index((retractall_u0), 1, mpred_core, mpred_core).
index((clause_u), 1, mpred_core, mpred_core).
index((clause_u), 2, mpred_core, mpred_core).
index((clause_u), 3, mpred_core, mpred_core).
index((lookup_u), 1, mpred_core, mpred_core).
index((mpred_load_term), 1, mpred_core, mpred_core).
index((pos_2_neg), 2, mpred_core, mpred_core).
index((not_not_ignore_mnotrace), 1, mpred_core, mpred_core).
index((mpred_trace_all), 0, mpred_core, mpred_core).
index((really_mpred_mark), 4, mpred_core, mpred_core).
index((unassertable), 1, mpred_core, mpred_core).
index((log_failure_red), 0, mpred_core, mpred_core).
index((convention_to_symbolic_mt), 4, mpred_core, mpred_core).
index((attvar_op_fully), 2, mpred_core, mpred_core).
index((closest_u), 2, mpred_core, mpred_core).
index((pred_check), 1, mpred_core, mpred_core).
index((pp_why), 0, mpred_core, mpred_core).
index((get_consequent_functor), 3, mpred_core, mpred_core).
index((is_user_fact), 1, mpred_core, mpred_core).
index((mpred_retract_i_or_warn_1), 1, mpred_core, mpred_core).
index((mpred_is_silient), 0, mpred_core, mpred_core).
index((pp_why), 1, mpred_core, mpred_core).
index((bad_head_pred), 1, mpred_core, mpred_core).
index((get_mpred_current_db), 1, mpred_core, mpred_core).
index((mpred_call_no_bc0), 1, mpred_core, mpred_core).
index((to_real_mt), 3, mpred_core, mpred_core).
index((all_closed), 1, mpred_core, mpred_core).
index((convention_to_mt), 4, mpred_core, mpred_core).
index((copy_term_vn), 2, mpred_core, mpred_core).
index((remove_meta_wrapper), 2, mpred_core, mpred_core).
index((mpred_undo1), 1, mpred_core, mpred_core).
index((convention_to_symbolic_mt_ec), 4, mpred_core, mpred_core).
index((mpred_retract_i_or_warn_0), 1, mpred_core, mpred_core).
index((push_current_choice), 1, mpred_core, mpred_core).
index((get_fc_mode), 3, mpred_core, mpred_core).
index((mpred_rem_support_if_exists), 2, mpred_core, mpred_core).
index((get_tms_mode), 2, mpred_core, mpred_core).
index((stop_trace), 1, mpred_core, mpred_core).
index((with_mpred_trace_exec), 1, mpred_core, mpred_core).
index((select_next_fact), 1, mpred_core, mpred_core).
index((supporters_list), 2, mpred_core, mpred_core).
index((triggerSupports), 2, mpred_core, mpred_core).
index((well_founded), 1, mpred_core, mpred_core).
index((well_founded_list), 2, mpred_core, mpred_core).
index((do_assumpts), 2, mpred_core, mpred_core).
index((mpred_do_fcnt), 2, mpred_core, mpred_core).
index((mpred_do_fcpt), 2, mpred_core, mpred_core).
index((mpred_fwc1), 1, mpred_core, mpred_core).
index((mpred_do_rule), 1, mpred_core, mpred_core).
index((mpred_descendant1), 3, mpred_core, mpred_core).
index((mpred_eval_rhs1), 2, mpred_core, mpred_core).
index((mpred_nf1), 2, mpred_core, mpred_core).
index((mpred_post1), 2, mpred_core, mpred_core).
index((mpred_withdraw), 1, mpred_core, mpred_core).
index((mpred_withdraw), 2, mpred_core, mpred_core).
index((mpred_remove), 1, mpred_core, mpred_core).
index((mpred_remove), 2, mpred_core, mpred_core).
index((mpred_post1), 2, mpred_core, mpred_core).
index((mpred_pp_db_justification1), 3, mpred_core, mpred_core).
index((mpred_pp_db_justifications2), 4, mpred_core, mpred_core).
index((mpred_spy1), 3, mpred_core, mpred_core).
index((mpred_unfwc_check_triggers0), 1, mpred_core, mpred_core).
index((mpred_unfwc1), 1, mpred_core, mpred_core).
index((mpred_why1), 1, mpred_core, mpred_core).
index((mpred_blast), 1, mpred_core, mpred_core).
index((a), 2, mpred_expansion, mpred_expansion).
index((acceptable_xform), 2, mpred_expansion, mpred_expansion).
index((additiveOp), 1, mpred_expansion, mpred_expansion).
index((alt_calls), 1, mpred_expansion, mpred_expansion).
index((any_op_to_call_op), 2, mpred_expansion, mpred_expansion).
index((as_is_term), 1, mpred_expansion, mpred_expansion).
index((as_is_term), 1, mpred_expansion, mpred_expansion).
index((as_list), 2, mpred_expansion, mpred_expansion).
index((cheaply_u), 1, mpred_expansion, mpred_expansion).
index((cheaply_u), 1, mpred_expansion, mpred_expansion).
index((maybe_prepend_mt), 3, mpred_expansion, mpred_expansion).
index((compare_op), 4, mpred_expansion, mpred_expansion).
index((comparitiveOp), 1, mpred_expansion, mpred_expansion).
index((compound_all_open), 1, mpred_expansion, mpred_expansion).
index((conjoin_l), 3, mpred_expansion, mpred_expansion).
index((try_expand_head), 3, mpred_expansion, mpred_expansion).
index((db_expand_0), 3, mpred_expansion, mpred_expansion).
index((db_expand_chain), 3, mpred_expansion, mpred_expansion).
index((db_expand_final), 3, mpred_expansion, mpred_expansion).
index((db_expand_maplist), 5, mpred_expansion, mpred_expansion).
index((db_op_sentence), 4, mpred_expansion, mpred_expansion).
index((db_op_simpler), 3, mpred_expansion, mpred_expansion).
index((db_quf), 4, mpred_expansion, mpred_expansion).
index((db_quf_l), 5, mpred_expansion, mpred_expansion).
index((db_quf_l_0), 5, mpred_expansion, mpred_expansion).
index((default_te), 3, mpred_expansion, mpred_expansion).
index((demodulize), 3, mpred_expansion, mpred_expansion).
index((remodulize), 3, mpred_expansion, mpred_expansion).
index((replaced_module), 3, mpred_expansion, mpred_expansion).
index((fully_expand_clause_now), 3, mpred_expansion, mpred_expansion).
index((do_expand_args), 3, mpred_expansion, mpred_expansion).
index((do_expand_args_l), 3, mpred_expansion, mpred_expansion).
index((do_expand_args_pa), 4, mpred_expansion, mpred_expansion).
index((ex_argIsa), 3, mpred_expansion, mpred_expansion).
index((exact_args), 1, mpred_expansion, mpred_expansion).
index((exact_args0), 1, mpred_expansion, mpred_expansion).
index((expand_isEach_or_fail), 2, mpred_expansion, mpred_expansion).
index((expand_goal_correct_argIsa), 2, mpred_expansion, mpred_expansion).
index((expand_props), 3, mpred_expansion, mpred_expansion).
index((expand_props), 4, mpred_expansion, mpred_expansion).
index((expanded_different), 2, mpred_expansion, mpred_expansion).
index((expanded_different_1), 2, mpred_expansion, mpred_expansion).
index((expanded_different_ic), 2, mpred_expansion, mpred_expansion).
index((fix_negations), 2, mpred_expansion, mpred_expansion).
index((fixed_negations), 2, mpred_expansion, mpred_expansion).
index((foreach_arg), 7, mpred_expansion, mpred_expansion).
index((from_univ), 4, mpred_expansion, mpred_expansion).
index((fully_expand), 2, mpred_expansion, mpred_expansion).
index((fully_expand), 3, mpred_expansion, mpred_expansion).
index((fully_expand_clause), 3, mpred_expansion, mpred_expansion).
index((fully_expand_goal), 3, mpred_expansion, mpred_expansion).
index((fully_expand_head), 3, mpred_expansion, mpred_expansion).
index((fully_expand_clause_now), 3, mpred_expansion, mpred_expansion).
index((fully_expand_real), 3, mpred_expansion, mpred_expansion).
index((fully_expand_clause_now), 3, mpred_expansion, mpred_expansion).
index((functor_declares_collectiontype), 2, mpred_expansion, mpred_expansion).
index((functor_declares_instance), 2, mpred_expansion, mpred_expansion).
index((functor_declares_instance_0), 2, mpred_expansion, mpred_expansion).
index((holds_args), 2, mpred_expansion, mpred_expansion).
index((same_terms), 2, mpred_expansion, mpred_expansion).
index((infix_op), 2, mpred_expansion, mpred_expansion).
index((instTypePropsToType), 2, mpred_expansion, mpred_expansion).
index((into_functor_form), 3, mpred_expansion, mpred_expansion).
index((into_functor_form), 5, mpred_expansion, mpred_expansion).
index((into_mpred_form), 2, mpred_expansion, mpred_expansion).
index((into_mpred_form6), 6, mpred_expansion, mpred_expansion).
index((into_mpred_form_ilc), 2, mpred_expansion, mpred_expansion).
index((is_arity_pred), 1, mpred_expansion, mpred_expansion).
index((is_meta_functor), 3, mpred_expansion, mpred_expansion).
index((is_pred_declarer), 1, mpred_expansion, mpred_expansion).
index((is_relation_type), 1, mpred_expansion, mpred_expansion).
index((is_stripped_module), 1, mpred_expansion, mpred_expansion).
index((is_unit), 1, mpred_expansion, mpred_expansion).
index((is_unit_like), 1, mpred_expansion, mpred_expansion).
index((post_expansion), 3, mpred_expansion, mpred_expansion).
index((is_unit_functor), 1, mpred_expansion, mpred_expansion).
index((listToE), 2, mpred_expansion, mpred_expansion).
index((map_f), 2, mpred_expansion, mpred_expansion).
index((mpred_expand_rule), 2, mpred_expansion, mpred_expansion).
index((must_expand), 1, mpred_expansion, mpred_expansion).
index((must_remodulize), 3, mpred_expansion, mpred_expansion).
index((recommify), 2, mpred_expansion, mpred_expansion).
index((recommify), 3, mpred_expansion, mpred_expansion).
index((reduce_clause), 3, mpred_expansion, mpred_expansion).
index((reduce_clause_from_fwd), 3, mpred_expansion, mpred_expansion).
index((same_terms), 2, mpred_expansion, mpred_expansion).
index((show_doall), 1, mpred_expansion, mpred_expansion).
index((string_to_mws), 2, mpred_expansion, mpred_expansion).
index((simply_functors), 3, mpred_expansion, mpred_expansion).
index((to_reduced_hb), 4, mpred_expansion, mpred_expansion).
index((transform_functor_holds), 5, mpred_expansion, mpred_expansion).
index((transform_holds), 3, mpred_expansion, mpred_expansion).
index((transform_holds_3), 3, mpred_expansion, mpred_expansion).
index((transitive_lc_nr), 3, mpred_expansion, mpred_expansion).
index((translate_args), 9, mpred_expansion, mpred_expansion).
index((translateListOps), 8, mpred_expansion, mpred_expansion).
index((translateOneArg), 8, mpred_expansion, mpred_expansion).
index((was_mpred_isa), 3, mpred_expansion, mpred_expansion).
index((was_isa), 3, mpred_expansion, mpred_expansion).
index((was_isa0), 3, mpred_expansion, mpred_expansion).
index((to_isa_out), 3, mpred_expansion, mpred_expansion).
index((mpred_expansion_file), 0, mpred_expansion, mpred_expansion).
index((expand_kif_string), 2, mpred_expansion, mpred_expansion).
index((temp_comp), 4, mpred_expansion, mpred_expansion).
index((get_ruleRewrite), 2, mpred_expansion, mpred_expansion).
index((expand_kif_string_or_fail), 3, mpred_expansion, mpred_expansion).
index((to_predicate_isas), 2, mpred_expansion, mpred_expansion).
index((append_as_first_arg), 3, mpred_expansion, mpred_expansion).
index((try_expand_head), 3, mpred_expansion, mpred_expansion).
index((expand_isEach_or_fail), 2, mpred_expansion, mpred_expansion).
index((is_elist_functor), 1, mpred_expansion, mpred_expansion).
index((relax_term), 6, mpred_hooks, mpred_hooks).
index((fix_sentence), 2, mpred_hooks, mpred_hooks).
index((holds_f), 1, mpred_hooks, mpred_hooks).
index((holds_f), 2, mpred_hooks, mpred_hooks).
index((holds_f), 3, mpred_hooks, mpred_hooks).
index((holds_f), 4, mpred_hooks, mpred_hooks).
index((holds_f), 5, mpred_hooks, mpred_hooks).
index((holds_f), 6, mpred_hooks, mpred_hooks).
index((holds_f), 7, mpred_hooks, mpred_hooks).
index((holds_f), 8, mpred_hooks, mpred_hooks).
index((holds_plist_t), 2, mpred_hooks, mpred_hooks).
index((holds_relaxed_0_t), 4, mpred_hooks, mpred_hooks).
index((holds_relaxed_t), 3, mpred_hooks, mpred_hooks).
index((holds_t), 1, mpred_hooks, mpred_hooks).
index((holds_t), 2, mpred_hooks, mpred_hooks).
index((holds_t), 3, mpred_hooks, mpred_hooks).
index((holds_t), 4, mpred_hooks, mpred_hooks).
index((holds_t), 5, mpred_hooks, mpred_hooks).
index((holds_t), 6, mpred_hooks, mpred_hooks).
index((holds_t), 7, mpred_hooks, mpred_hooks).
index((holds_t), 8, mpred_hooks, mpred_hooks).
index((holds_f_p2), 2, mpred_hooks, mpred_hooks).
index((holds_relaxed_0_f), 4, mpred_hooks, mpred_hooks).
index((holds_relaxed_f), 3, mpred_hooks, mpred_hooks).
index((assertion_f), 1, mpred_hooks, mpred_hooks).
index((assertion_t), 1, mpred_hooks, mpred_hooks).
index((call_f), 3, mpred_hooks, mpred_hooks).
index((call_f), 4, mpred_hooks, mpred_hooks).
index((call_f), 5, mpred_hooks, mpred_hooks).
index((call_f), 6, mpred_hooks, mpred_hooks).
index((call_f), 7, mpred_hooks, mpred_hooks).
index((call_f), 8, mpred_hooks, mpred_hooks).
index((call_f), 9, mpred_hooks, mpred_hooks).
index((call_mt_f), 4, mpred_hooks, mpred_hooks).
index((call_mt_f), 5, mpred_hooks, mpred_hooks).
index((call_mt_f), 6, mpred_hooks, mpred_hooks).
index((call_mt_f), 7, mpred_hooks, mpred_hooks).
index((call_mt_f), 8, mpred_hooks, mpred_hooks).
index((call_mt_f), 9, mpred_hooks, mpred_hooks).
index((call_mt_f), 10, mpred_hooks, mpred_hooks).
index((call_mt_f), 11, mpred_hooks, mpred_hooks).
index((call_mt_t), 4, mpred_hooks, mpred_hooks).
index((call_mt_t), 5, mpred_hooks, mpred_hooks).
index((call_mt_t), 6, mpred_hooks, mpred_hooks).
index((call_mt_t), 7, mpred_hooks, mpred_hooks).
index((call_mt_t), 8, mpred_hooks, mpred_hooks).
index((call_mt_t), 9, mpred_hooks, mpred_hooks).
index((call_mt_t), 10, mpred_hooks, mpred_hooks).
index((call_mt_t), 11, mpred_hooks, mpred_hooks).
index((call_which_t), 3, mpred_hooks, mpred_hooks).
index((call_which_t), 4, mpred_hooks, mpred_hooks).
index((call_which_t), 5, mpred_hooks, mpred_hooks).
index((call_which_t), 6, mpred_hooks, mpred_hooks).
index((call_which_t), 7, mpred_hooks, mpred_hooks).
index((call_which_t), 8, mpred_hooks, mpred_hooks).
index((call_which_t), 9, mpred_hooks, mpred_hooks).
index((call_whichlist_t), 3, mpred_hooks, mpred_hooks).
index((callable_tf), 2, mpred_hooks, mpred_hooks).
index((xcall_f), 1, mpred_hooks, mpred_hooks).
index((xcall_f), 2, mpred_hooks, mpred_hooks).
index((xcall_f), 3, mpred_hooks, mpred_hooks).
index((xcall_f), 4, mpred_hooks, mpred_hooks).
index((xcall_f), 5, mpred_hooks, mpred_hooks).
index((xcall_f), 6, mpred_hooks, mpred_hooks).
index((xcall_f), 7, mpred_hooks, mpred_hooks).
index((xcall_f), 8, mpred_hooks, mpred_hooks).
index((xcall_f), 9, mpred_hooks, mpred_hooks).
index((xcall_f), 10, mpred_hooks, mpred_hooks).
index((xcall_t), 1, mpred_hooks, mpred_hooks).
index((xcall_t), 2, mpred_hooks, mpred_hooks).
index((xcall_t), 3, mpred_hooks, mpred_hooks).
index((xcall_t), 4, mpred_hooks, mpred_hooks).
index((xcall_t), 5, mpred_hooks, mpred_hooks).
index((xcall_t), 6, mpred_hooks, mpred_hooks).
index((xcall_t), 7, mpred_hooks, mpred_hooks).
index((xcall_t), 8, mpred_hooks, mpred_hooks).
index((xcall_t), 9, mpred_hooks, mpred_hooks).
index((xcall_t), 10, mpred_hooks, mpred_hooks).
index((mpred_f), 1, mpred_hooks, mpred_hooks).
index((which_f), 1, mpred_hooks, mpred_hooks).
index((which_t), 1, mpred_hooks, mpred_hooks).
index((add_arg_parts_of_speech), 4, mpred_hooks, mpred_hooks).
index((verb_after_arg), 3, mpred_hooks, mpred_hooks).
index((local_qh_mpred_isa), 2, mpred_hooks, mpred_hooks).
index((print_sentence), 1, mpred_hooks, mpred_hooks).
index((argIsa_call_or_undressed), 4, mpred_hooks, mpred_hooks).
index((compute_value), 2, mpred_hooks, mpred_hooks).
index((compute_value_no_dice), 2, mpred_hooks, mpred_hooks).
index((flatten_append), 3, mpred_hooks, mpred_hooks).
index((if_result), 2, mpred_hooks, mpred_hooks).
index((insert_into), 4, mpred_hooks, mpred_hooks).
index((into_plist), 2, mpred_hooks, mpred_hooks).
index((into_plist_arities), 4, mpred_hooks, mpred_hooks).
index((inverse_args), 2, mpred_hooks, mpred_hooks).
index((isCycPredArity_ignoreable), 2, mpred_hooks, mpred_hooks).
index((list_update_op), 3, mpred_hooks, mpred_hooks).
index((mpred_fact_arity), 2, mpred_hooks, mpred_hooks).
index((mpred_fa_call), 3, mpred_hooks, mpred_hooks).
index((mpred_plist_t), 2, mpred_hooks, mpred_hooks).
index((never_mpred_tcall), 1, mpred_hooks, mpred_hooks).
index((prologHybridFact), 1, mpred_hooks, mpred_hooks).
index((replace_arg), 4, mpred_hooks, mpred_hooks).
index((replace_nth_arglist), 4, mpred_hooks, mpred_hooks).
index((replace_nth_ref), 5, mpred_hooks, mpred_hooks).
index((same_vars), 2, mpred_hooks, mpred_hooks).
index((update_value), 3, mpred_hooks, mpred_hooks).
index((deducedSimply), 1, mpred_kb_ops, mpred_kb_ops).
index((get_consequent), 2, mpred_kb_ops, mpred_kb_ops).
index((how_to_op), 2, mpred_kb_ops, mpred_kb_ops).
index((is_callable), 1, mpred_kb_ops, mpred_kb_ops).
index((lookup_inverted_op), 3, mpred_kb_ops, mpred_kb_ops).
index((mpred_op), 2, mpred_kb_ops, mpred_kb_ops).
index((naf), 1, mpred_kb_ops, mpred_kb_ops).
index((oncely), 1, mpred_kb_ops, mpred_kb_ops).
index((reduce_mpred_op), 2, mpred_kb_ops, mpred_kb_ops).
index((second_order), 2, mpred_kb_ops, mpred_kb_ops).
index((whenAnd), 2, mpred_kb_ops, mpred_kb_ops).
index((if_missing1), 1, mpred_kb_ops, mpred_kb_ops).
index((ain_minfo), 2, mpred_kb_ops, mpred_kb_ops).
index((cnstrn0), 2, mpred_kb_ops, mpred_kb_ops).
index((physical_side_effect), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_update_literal), 4, mpred_kb_ops, mpred_kb_ops).
index((cnstrn), 1, mpred_kb_ops, mpred_kb_ops).
index((predicate_to_goal), 2, mpred_kb_ops, mpred_kb_ops).
index((map_unless), 4, mpred_kb_ops, mpred_kb_ops).
index((mpred_update_literal), 4, mpred_kb_ops, mpred_kb_ops).
index((cnstrn), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_facts_only), 1, mpred_kb_ops, mpred_kb_ops).
index((pred_head), 2, mpred_kb_ops, mpred_kb_ops).
index((ain_minfo), 2, mpred_kb_ops, mpred_kb_ops).
index((cnstrn), 2, mpred_kb_ops, mpred_kb_ops).
index((ain_minfo_2), 2, mpred_kb_ops, mpred_kb_ops).
index((cnstrn0), 2, mpred_kb_ops, mpred_kb_ops).
index((physical_side_effect), 1, mpred_kb_ops, mpred_kb_ops).
index((predicate_to_goal), 2, mpred_kb_ops, mpred_kb_ops).
index((mpred_kb_ops_file), 0, mpred_kb_ops, mpred_kb_ops).
index((mpred_wfflist), 2, mpred_kb_ops, mpred_kb_ops).
index((mpred_wff), 3, mpred_kb_ops, mpred_kb_ops).
index((attvar_op), 2, mpred_kb_ops, mpred_kb_ops).
index((no_side_effects), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_non_neg_literal), 1, mpred_kb_ops, mpred_kb_ops).
index((retract_mu), 1, mpred_kb_ops, mpred_kb_ops).
index((assert_mu), 4, mpred_kb_ops, mpred_kb_ops).
index((asserta_mu), 2, mpred_kb_ops, mpred_kb_ops).
index((asserta_mu), 1, mpred_kb_ops, mpred_kb_ops).
index((assertz_mu), 2, mpred_kb_ops, mpred_kb_ops).
index((assertz_mu), 1, mpred_kb_ops, mpred_kb_ops).
index((ruleBackward0), 2, mpred_kb_ops, mpred_kb_ops).
index((ruleBackward), 2, mpred_kb_ops, mpred_kb_ops).
index((fwd_ok), 1, mpred_kb_ops, mpred_kb_ops).
index((repropagate_meta_wrapper_rule), 1, mpred_kb_ops, mpred_kb_ops).
index((repropagate_1), 1, mpred_kb_ops, mpred_kb_ops).
index((repropagate_0), 1, mpred_kb_ops, mpred_kb_ops).
index((repropagate), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_facts_and_universe), 1, mpred_kb_ops, mpred_kb_ops).
index((rescan_pfc), 0, mpred_kb_ops, mpred_kb_ops).
index((pred_r0), 1, mpred_kb_ops, mpred_kb_ops).
index((pred_t0), 1, mpred_kb_ops, mpred_kb_ops).
index((has_db_clauses), 1, mpred_kb_ops, mpred_kb_ops).
index((pred_u2), 1, mpred_kb_ops, mpred_kb_ops).
index((pred_u1), 1, mpred_kb_ops, mpred_kb_ops).
index((pred_u0), 1, mpred_kb_ops, mpred_kb_ops).
index((pred_all), 1, mpred_kb_ops, mpred_kb_ops).
index((meta_wrapper_rule), 1, mpred_kb_ops, mpred_kb_ops).
index((rewritten_metawrapper), 1, mpred_kb_ops, mpred_kb_ops).
index((nonfact_metawrapper), 1, mpred_kb_ops, mpred_kb_ops).
index((pred_head_all), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_prove_neg), 1, mpred_kb_ops, mpred_kb_ops).
index((is_resolved), 1, mpred_kb_ops, mpred_kb_ops).
index((compute_resolve), 3, mpred_kb_ops, mpred_kb_ops).
index((compute_resolve), 5, mpred_kb_ops, mpred_kb_ops).
index((no_side_effects), 1, mpred_kb_ops, mpred_kb_ops).
index((should_call_for_facts), 3, mpred_kb_ops, mpred_kb_ops).
index((should_call_for_facts), 1, mpred_kb_ops, mpred_kb_ops).
index((clause_or_call), 2, mpred_kb_ops, mpred_kb_ops).
index((is_relative), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_non_neg_literal), 1, mpred_kb_ops, mpred_kb_ops).
index((is_reprop_0), 1, mpred_kb_ops, mpred_kb_ops).
index((is_reprop), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_literal_nv), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_is_assertable), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_cleanup_0), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_cleanup), 2, mpred_kb_ops, mpred_kb_ops).
index((mpred_cleanup), 0, mpred_kb_ops, mpred_kb_ops).
index((mpred_negation_w_neg), 2, mpred_kb_ops, mpred_kb_ops).
index((has_cl), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_ignored), 1, mpred_kb_ops, mpred_kb_ops).
index((maybeSupport), 2, mpred_kb_ops, mpred_kb_ops).
index((pfcBC_Cache), 1, mpred_kb_ops, mpred_kb_ops).
index((pfcBC_NoFacts_TRY), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_slow_search), 0, mpred_kb_ops, mpred_kb_ops).
index((pfcBC_NoFacts), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_bc_only0), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_bc_only), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_call_with_no_triggers_uncaugth), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_call_with_no_triggers_bound), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_call_with_no_triggers), 1, mpred_kb_ops, mpred_kb_ops).
index((call_with_bc_triggers), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_call_1), 3, mpred_kb_ops, mpred_kb_ops).
index((mpred_call_0), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_call_only_facts), 2, mpred_kb_ops, mpred_kb_ops).
index((mpred_call_only_facts), 1, mpred_kb_ops, mpred_kb_ops).
index((call_u_req), 1, mpred_kb_ops, mpred_kb_ops).
index((neg_in_code), 1, mpred_kb_ops, mpred_kb_ops).
index((neg_in_code0), 1, mpred_kb_ops, mpred_kb_ops).
index((trigger_supporters_list), 2, mpred_kb_ops, mpred_kb_ops).
index((spft_precanonical), 3, mpred_kb_ops, mpred_kb_ops).
index((mpred_get_support_precanonical), 2, mpred_kb_ops, mpred_kb_ops).
index((support_ok_via_clause_body), 3, mpred_kb_ops, mpred_kb_ops).
index((support_ok_via_clause_body), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_get_support_via_clause_db), 2, mpred_kb_ops, mpred_kb_ops).
index((mpred_get_support_via_sentence), 2, mpred_kb_ops, mpred_kb_ops).
index((mpred_get_support_one), 2, mpred_kb_ops, mpred_kb_ops).
index((mpred_get_support_precanonical_plus_more), 2, mpred_kb_ops, mpred_kb_ops).
index((mpred_deep_support0), 2, mpred_kb_ops, mpred_kb_ops).
index((mpred_deep_support), 2, mpred_kb_ops, mpred_kb_ops).
index((user_atom), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_scan_tms), 1, mpred_kb_ops, mpred_kb_ops).
index((well_founded), 2, mpred_kb_ops, mpred_kb_ops).
index((mpred_tms_supported0), 3, mpred_kb_ops, mpred_kb_ops).
index((mpred_tms_supported), 3, mpred_kb_ops, mpred_kb_ops).
index((mpred_tms_supported), 2, mpred_kb_ops, mpred_kb_ops).
index((mpred_remove_file_support), 1, mpred_kb_ops, mpred_kb_ops).
index((without_running), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_run_resume), 0, mpred_kb_ops, mpred_kb_ops).
index((mpred_run_pause), 0, mpred_kb_ops, mpred_kb_ops).
index((which_missing_argnum), 2, mpred_kb_ops, mpred_kb_ops).
index((if_missing_mask), 4, mpred_kb_ops, mpred_kb_ops).
index((if_missing_mask), 3, mpred_kb_ops, mpred_kb_ops).
index((is_already_supported), 3, mpred_kb_ops, mpred_kb_ops).
index((clause_asserted_local), 1, mpred_kb_ops, mpred_kb_ops).
index((correctify_support), 2, mpred_kb_ops, mpred_kb_ops).
index((pfcVersion), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_current_op_support), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_freeLastArg), 2, mpred_kb_ops, mpred_kb_ops).
index((pfcVerifyMissing), 3, mpred_kb_ops, mpred_kb_ops).
index((map_first_arg), 3, mpred_kb_ops, mpred_kb_ops).
index((map_first_arg), 2, mpred_kb_ops, mpred_kb_ops).
index((map_literals), 3, mpred_kb_ops, mpred_kb_ops).
index((map_literals), 2, mpred_kb_ops, mpred_kb_ops).
index((update_single_valued_arg), 3, mpred_kb_ops, mpred_kb_ops).
index((has_body_atom), 2, mpred_kb_ops, mpred_kb_ops).
index((is_action_body), 1, mpred_kb_ops, mpred_kb_ops).
index((is_bc_body), 1, mpred_kb_ops, mpred_kb_ops).
index((is_fc_body), 1, mpred_kb_ops, mpred_kb_ops).
index((wac), 0, mpred_kb_ops, mpred_kb_ops).
index((bwc), 0, mpred_kb_ops, mpred_kb_ops).
index((fwc), 0, mpred_kb_ops, mpred_kb_ops).
index((cwc), 0, mpred_kb_ops, mpred_kb_ops).
index((mpred_rewrap_h), 2, mpred_kb_ops, mpred_kb_ops).
index((mpred_is_info), 1, mpred_kb_ops, mpred_kb_ops).
index((ain_minfo), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_rule_hb_0), 3, mpred_kb_ops, mpred_kb_ops).
index((mpred_rule_hb), 3, mpred_kb_ops, mpred_kb_ops).
index((all_different_head_vals_2), 2, mpred_kb_ops, mpred_kb_ops).
index((all_different_head_vals), 1, mpred_kb_ops, mpred_kb_ops).
index((sub_term_v), 2, mpred_kb_ops, mpred_kb_ops).
index((sub_term_eq), 2, mpred_kb_ops, mpred_kb_ops).
index((mpred_pbody_f), 5, mpred_kb_ops, mpred_kb_ops).
index((get_why), 4, mpred_kb_ops, mpred_kb_ops).
index((mpred_pbody), 5, mpred_kb_ops, mpred_kb_ops).
index((pfc_provide_storage_op), 2, mpred_kb_ops, mpred_kb_ops).
index((is_retract_first), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_is_taut), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_is_tautology), 1, mpred_kb_ops, mpred_kb_ops).
index((assert_eq_quitely), 1, mpred_kb_ops, mpred_kb_ops).
index((retract_eq_quitely_f), 1, mpred_kb_ops, mpred_kb_ops).
index((retract_eq_quitely), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_each_literal), 2, mpred_kb_ops, mpred_kb_ops).
index((has_functor), 1, mpred_kb_ops, mpred_kb_ops).
index((make_uu_remove), 1, mpred_kb_ops, mpred_kb_ops).
index((match_source_ref1), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_nochaining), 1, mpred_kb_ops, mpred_kb_ops).
index((erase_w_attvars), 2, mpred_kb_ops, mpred_kb_ops).
index((call_s2), 1, mpred_kb_ops, mpred_kb_ops).
index((call_s), 1, mpred_kb_ops, mpred_kb_ops).
index((clauseq_s), 3, mpred_kb_ops, mpred_kb_ops).
index((clause_s), 3, mpred_kb_ops, mpred_kb_ops).
index((assertz_s), 1, mpred_kb_ops, mpred_kb_ops).
index((asserta_s), 1, mpred_kb_ops, mpred_kb_ops).
index((lookq_s), 2, mpred_kb_ops, mpred_kb_ops).
index((lookq_s), 1, mpred_kb_ops, mpred_kb_ops).
index((lookup_s), 2, mpred_kb_ops, mpred_kb_ops).
index((lookup_s), 1, mpred_kb_ops, mpred_kb_ops).
index((retract_s), 1, mpred_kb_ops, mpred_kb_ops).
index((clause_s), 2, mpred_kb_ops, mpred_kb_ops).
index((retractall_s), 1, mpred_kb_ops, mpred_kb_ops).
index((assert_s), 1, mpred_kb_ops, mpred_kb_ops).
index((listing_s), 1, mpred_kb_ops, mpred_kb_ops).
index((add_side_effect), 2, mpred_kb_ops, mpred_kb_ops).
index((record_se), 0, mpred_kb_ops, mpred_kb_ops).
index((mpred_is_builtin), 1, mpred_kb_ops, mpred_kb_ops).
index((is_mpred_action), 1, mpred_kb_ops, mpred_kb_ops).
index((set_prolog_stack_gb), 1, mpred_kb_ops, mpred_kb_ops).
index((w_get_fa), 3, mpred_kb_ops, mpred_kb_ops).
index((f_to_mfa), 4, mpred_kb_ops, mpred_kb_ops).
index((is_side_effect_disabled), 0, mpred_kb_ops, mpred_kb_ops).
index((mreq), 1, mpred_kb_ops, mpred_kb_ops).
index((check_real_context_module), 0, mpred_kb_ops, mpred_kb_ops).
index((check_context_module), 0, mpred_kb_ops, mpred_kb_ops).
index((lookup_inverted_op), 3, mpred_kb_ops, mpred_kb_ops).
index((how_to_op), 2, mpred_kb_ops, mpred_kb_ops).
index((reduce_mpred_op), 2, mpred_kb_ops, mpred_kb_ops).
index((second_order), 2, mpred_kb_ops, mpred_kb_ops).
index((assert_mu), 1, mpred_kb_ops, mpred_kb_ops).
index((assertz_mu), 2, mpred_kb_ops, mpred_kb_ops).
index((assertz_mu), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_op), 2, mpred_kb_ops, mpred_kb_ops).
index((mpred_retry), 1, mpred_kb_ops, mpred_kb_ops).
index((has_functor), 1, mpred_kb_ops, mpred_kb_ops).
index((call_s), 1, mpred_kb_ops, mpred_kb_ops).
index((call_s2), 1, mpred_kb_ops, mpred_kb_ops).
index((asserta_s), 1, mpred_kb_ops, mpred_kb_ops).
index((assert_s), 1, mpred_kb_ops, mpred_kb_ops).
index((assertz_s), 1, mpred_kb_ops, mpred_kb_ops).
index((retract_s), 1, mpred_kb_ops, mpred_kb_ops).
index((retractall_s), 1, mpred_kb_ops, mpred_kb_ops).
index((clause_s), 2, mpred_kb_ops, mpred_kb_ops).
index((clause_s), 3, mpred_kb_ops, mpred_kb_ops).
index((lookup_s), 1, mpred_kb_ops, mpred_kb_ops).
index((lookup_s), 2, mpred_kb_ops, mpred_kb_ops).
index((lookq_s), 2, mpred_kb_ops, mpred_kb_ops).
index((lookq_s), 1, mpred_kb_ops, mpred_kb_ops).
index((update_single_valued_arg), 3, mpred_kb_ops, mpred_kb_ops).
index((ruleBackward), 2, mpred_kb_ops, mpred_kb_ops).
index((retract_eq_quitely_f), 1, mpred_kb_ops, mpred_kb_ops).
index((neg_in_code), 1, mpred_kb_ops, mpred_kb_ops).
index((neg_in_code0), 1, mpred_kb_ops, mpred_kb_ops).
index((mreq), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_rule_hb), 3, mpred_kb_ops, mpred_kb_ops).
index((mpred_remove_file_support), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_nochaining), 1, mpred_kb_ops, mpred_kb_ops).
index((mpred_negation_w_neg), 2, mpred_kb_ops, mpred_kb_ops).
index((mpred_negation_w_neg), 2, mpred_kb_ops, mpred_kb_ops).
index((map_first_arg), 2, mpred_kb_ops, mpred_kb_ops).
index((mpred_rule_hb), 3, mpred_kb_ops, mpred_kb_ops).
index((mpred_rule_hb_0), 3, mpred_kb_ops, mpred_kb_ops).
index((is_side_effect_disabled), 0, mpred_kb_ops, mpred_kb_ops).
index((is_resolved), 1, mpred_kb_ops, mpred_kb_ops).
index((is_fc_body), 1, mpred_kb_ops, mpred_kb_ops).
index((is_bc_body), 1, mpred_kb_ops, mpred_kb_ops).
index((is_action_body), 1, mpred_kb_ops, mpred_kb_ops).
index((has_cl), 1, mpred_kb_ops, mpred_kb_ops).
index((has_body_atom), 2, mpred_kb_ops, mpred_kb_ops).
index((cwc), 0, mpred_kb_ops, mpred_kb_ops).
index((compute_resolve), 3, mpred_kb_ops, mpred_kb_ops).
index((clause_or_call), 2, mpred_kb_ops, mpred_kb_ops).
index((clause_or_call), 2, mpred_kb_ops, mpred_kb_ops).
index((check_context_module), 0, mpred_kb_ops, mpred_kb_ops).
index((call_with_bc_triggers), 1, mpred_kb_ops, mpred_kb_ops).
index((attvar_op), 2, mpred_kb_ops, mpred_kb_ops).
index((mpred_facts_and_universe), 1, mpred_kb_ops, mpred_kb_ops).
index((add_mpred_prop_gleaned), 2, mpred_props, mpred_props).
index((add_mpred_prop_gleaned_4), 4, mpred_props, mpred_props).
index((assert_arity), 2, mpred_props, mpred_props).
index((bad_arity), 2, mpred_props, mpred_props).
index((bad_pred_relation_name0), 2, mpred_props, mpred_props).
index((bad_pred_relation_name1), 2, mpred_props, mpred_props).
index((decl_mpred), 1, mpred_props, mpred_props).
index((decl_mpred), 2, mpred_props, mpred_props).
index((arity_no_bc), 2, mpred_props, mpred_props).
index((decl_mpred), 3, mpred_props, mpred_props).
index((decl_mpred_0), 2, mpred_props, mpred_props).
index((decl_mpred_2), 2, mpred_props, mpred_props).
index((decl_mpred_3), 3, mpred_props, mpred_props).
index((decl_mpred_4), 4, mpred_props, mpred_props).
index((define_maybe_exact), 2, mpred_props, mpred_props).
index((kb_shared), 2, mpred_props, mpred_props).
index((kb_shared), 3, mpred_props, mpred_props).
index((kb_shared), 4, mpred_props, mpred_props).
index((kb_shared), 5, mpred_props, mpred_props).
index((decl_mpred_mfa), 3, mpred_props, mpred_props).
index((decl_mpred_pi), 1, mpred_props, mpred_props).
index((decl_mpred_prolog), 1, mpred_props, mpred_props).
index((decl_mpred_prolog), 2, mpred_props, mpred_props).
index((decl_mpred_prolog), 3, mpred_props, mpred_props).
index((decl_mpred_prolog), 4, mpred_props, mpred_props).
index((decl_mpred_prolog), 5, mpred_props, mpred_props).
index((ensure_arity), 2, mpred_props, mpred_props).
index((functor_check_univ), 3, mpred_props, mpred_props).
index((get_arity), 3, mpred_props, mpred_props).
index((get_mpred_prop), 2, mpred_props, mpred_props).
index((get_mpred_prop), 3, mpred_props, mpred_props).
index((glean_pred_props_maybe), 1, mpred_props, mpred_props).
index((glean_pred_props_maybe_some), 1, mpred_props, mpred_props).
index((good_pred_relation_name), 2, mpred_props, mpred_props).
index((listprolog), 0, mpred_props, mpred_props).
index((pred_type_test), 2, mpred_props, mpred_props).
index((pred_type_test), 3, mpred_props, mpred_props).
index((pred_type_test2), 2, mpred_props, mpred_props).
index((mpred_props_file), 0, mpred_props, mpred_props).
index((mpred_userkb_file), 0, mpred_userkb, mpred_userkb).
